'use client';
import {useEffect,useState,useRef,type FormEvent} from 'react';
import {LockKeyhole,ArrowLeft,RefreshCw,LogOut,Copy,Check,Search,Radio,Users,Gavel} from 'lucide-react';
import {LocalClock} from '@/components/local-clock';
import {money} from '@/lib/game';
type Room={code:string;phase:string;humans:number;computers:number;lot:number;player:string;sold:number;spent:number};
type Data={rooms:Room[];stats:{total:number;waiting:number;underway:number;finished:number};next:string|null};
export default function Owner(){
 const [data,setData]=useState<Data|null>(null),[key,setKey]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[copied,setCopied]=useState(''),[updated,setUpdated]=useState('');const query=useRef('');
 async function load(append=false){setBusy(true);setError('');try{const response=await fetch('/api/owner?search='+encodeURIComponent(query.current)+(append&&data?.next?'&before='+data.next:''));const result=await response.json() as Data & {error:string};if(response.status===401){setData(null);return}if(!response.ok)throw new Error(result.error);setData(previous=>append&&previous?{...result,rooms:[...previous.rooms,...result.rooms]}:result);setUpdated(new Date().toLocaleTimeString())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});setKey('');const d=await r.json() as {error:string};if(!r.ok)throw new Error(d.error);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{const r=await fetch('/api/owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!r.ok)throw new Error('Could not sign out. Try again.');setData(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function copy(code:string){try{await navigator.clipboard.writeText(code);setCopied(code)}catch{setError('Copy this code manually: '+code)}}
 return <div className="owner-shell"><header className="owner-header"><a href="/"><ArrowLeft size={16}/>Back to auction</a><LocalClock/></header><div className="owner-title"><span className="eyebrow"><LockKeyhole size={15}/>OWNER ACCESS</span><h1>Your auction<br/><em>control room.</em></h1><p>A private overview of every room created on your website.</p></div>{error&&<p className="error" role="alert">{error}</p>}{!data?<form className="owner-login panel" onSubmit={login}><LockKeyhole size={30}/><h2>Only you have the key.</h2><p>Use your private owner key to view the room directory.</p><label htmlFor="owner-key">Owner access key</label><input id="owner-key" type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)} required maxLength={128}/><button className="primary-button" disabled={busy||!key}>{busy?'Checking…':'Open owner dashboard'}</button><small>Your key is never saved in browser storage.</small></form>:<><div className="owner-stats">{[['Total rooms',data.stats.total,Users],['Waiting to start',data.stats.waiting||0,Gavel],['Auctions underway',data.stats.underway||0,Radio],['Completed',data.stats.finished||0,Check]].map(([label,count,Icon])=>{const I=Icon as typeof Users;return <div className="panel" key={String(label)}><I size={20}/><strong>{String(count)}</strong><span>{String(label)}</span></div>})}</div><section className="owner-directory panel"><div className="owner-tools"><form onSubmit={e=>{e.preventDefault();query.current=search;void load()}}><Search size={18}/><input aria-label="Search room code" placeholder="Search room code…" value={search} maxLength={8} onChange={e=>setSearch(e.target.value.toUpperCase())}/><button disabled={busy}>Search</button></form><button disabled={busy} onClick={()=>load()}><RefreshCw size={15}/>Refresh</button><button disabled={busy} onClick={logout}><LogOut size={15}/>Sign out</button></div><p className="owner-note">Newest rooms first · Updated {updated} · Status shows saved auction progress, not who is currently online.</p><div className="owner-table"><table><thead><tr><th>Room ID</th><th>Status</th><th>Managers</th><th>Current lot</th><th>Sold / spending</th></tr></thead><tbody>{data.rooms.map(room=><tr key={room.code}><td><button className="owner-code" onClick={()=>copy(room.code)}>{room.code}{copied===room.code?<Check size={14}/>:<Copy size={14}/>}</button></td><td><span className={'room-pill phase-'+room.phase}>{room.phase==='lobby'?'Waiting':room.phase==='finished'?'Complete':'Underway'}</span></td><td>{room.humans} human<small>{room.computers} computer</small></td><td>{room.player}<small>Lot {room.lot}</small></td><td>{room.sold} players<small>{money(room.spent)}</small></td></tr>)}</tbody></table></div>{!data.rooms.length&&<p className="owner-empty">No rooms match this search.</p>}{data.next&&<button className="owner-more" disabled={busy} onClick={()=>load(true)}>{busy?'Loading…':'Load more rooms'}</button>}</section></>}</div>
}
