import assert from 'node:assert/strict';
const url='http://localhost:5173/api/room';
const users=[{}, {}, {}];
async function request(user,body,expected=200){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(user.cookie?{Cookie:user.cookie}:{})},body:JSON.stringify(body)});const cookie=r.headers.get('set-cookie');if(cookie)user.cookie=cookie.split(';')[0];const result=await r.json();assert.equal(r.status,expected,JSON.stringify(result));return result}
let room=await request(users[0],{action:'create',team:'CSK',name:'Test host'});
assert.equal(room.phase,'lobby');assert.equal(room.host,'you');assert.equal(room.seats.CSK.token,undefined);
const code=room.code;
await request(users[1],{action:'join',team:'CSK',name:'Guest',code},400);
room=await request(users[1],{action:'join',team:'MI',name:'Guest',code});assert.equal(room.host,'other');assert.equal(room.seats.MI.mine,true);
await request(users[1],{action:'start',code},400);
await request(users[2],{action:'bid',code,round:1,amount:200},403);
room=await request(users[0],{action:'start',code});assert.equal(Object.keys(room.seats).length,10);assert.equal(Object.values(room.seats).filter(s=>s.bot).length,8);
room=await request(users[0],{action:'bid',code,round:1,amount:200});assert.equal(room.leader,'CSK');
await request(users[1],{action:'bid',code,round:1,amount:200},400);
room=await request(users[1],{action:'bid',code,round:1,amount:220});assert.equal(room.leader,'MI');
await request(users[1],{action:'pass',code},400);
room=await request(users[0],{action:'pass',code});assert.ok(room.passed.includes('CSK'));
await request(users[0],{action:'bid',code,round:1,amount:240},400);
await request(users[2],{action:'join',code,team:'RCB',name:'Late'},400);
const reload=await fetch(url+'?code='+code,{headers:{Cookie:users[1].cookie}});assert.equal((await reload.json()).seats.MI.mine,true);
console.log('PASS: independent players, exclusive teams, host authority, private sessions, stale bid rejection, budget-backed bidding, pass and reconnect.');

const soloUser={};
let solo=await request(soloUser,{action:'create',team:'RCB',name:'Solo host',solo:true});
assert.equal(solo.phase,'lobby');assert.equal(solo.deadline,0);assert.equal(Object.values(solo.seats).filter(s=>s.bot).length,9);
await request(soloUser,{action:'bid',code:solo.code,round:1,amount:200},400);
const waiting=await fetch(url+'?code='+solo.code,{headers:{Cookie:soloUser.cookie}});
assert.equal((await waiting.json()).phase,'lobby');
solo=await request(soloUser,{action:'start',code:solo.code});assert.equal(solo.phase,'live');assert.ok(solo.deadline>Date.now());
console.log('PASS: solo room waits for explicit host start; no pre-start bidding.');

// Audience access is read-only and does not consume a playing seat.
const audience={};
const watched=await request(audience,{action:'watch',code});
assert.equal(watched.audience,true);assert.equal(watched.host,'other');
assert.ok(Object.values(watched.seats).every(s=>s.token===undefined&&!s.mine));
for(const action of ['start','bid','pass'])await request(audience,{action,code,round:1,amount:240},403);
const audienceReload=await fetch(url+'?code='+code+'&audience=1',{headers:{Cookie:audience.cookie}});
assert.equal(audienceReload.status,200);assert.equal((await audienceReload.json()).audience,true);
await request(audience,{action:'invented-action',code},400);
const fullHost={};
const full=await request(fullHost,{action:'create',name:'Capacity host',team:'CSK'});
for(const team of ['MI','RCB','KKR','SRH','RR','DC','PBKS','GT','LSG'])await request({},{action:'join',name:team,team,code:full.code});
const eleventh={};
const rejected=await request(eleventh,{action:'join',name:'Eleventh',team:'CSK',code:full.code},400);
assert.match(rejected.error,/10 playing seats/);
const fullAudience=await request(eleventh,{action:'watch',code:full.code});
assert.equal(Object.keys(fullAudience.seats).length,10);assert.equal(fullAudience.phase,'lobby');assert.equal(fullAudience.audience,true);
const repeated=await request(fullHost,{action:'join',name:'Duplicate',team:'MI',code:full.code});
assert.equal(Object.values(repeated.seats).filter(s=>s.mine).length,1);assert.equal(Object.keys(repeated.seats).length,10);
console.log('PASS: ten-seat cap, audience in full/live rooms, audience reconnect, no audience bids/start/pass, private tokens, duplicate join safety.');

await request(users[1],{action:'pause',code},400);
room=await request(users[0],{action:'pause',code});assert.ok(room.paused);const pauseState=room.paused;
await request(users[1],{action:'resume',code},400);
await request(users[1],{action:'bid',code,round:room.round,amount:240},400);
await request(audience,{action:'pause',code},403);
const pausedReload=await fetch(url+'?code='+code,{headers:{Cookie:users[0].cookie}});const pausedData=await pausedReload.json();assert.deepEqual(pausedData.paused,pauseState);assert.equal(pausedData.host,'you');
room=await request(users[0],{action:'resume',code});assert.equal(room.paused,undefined);assert.ok(room.deadline>=Date.now());
console.log('PASS: host-only pause/resume, paused bid rejection and authenticated paused-room reconnect.');
