'use client';
import {useState,useRef,type PointerEvent} from 'react';
import {ArrowLeft,ArrowRight,Gavel,Sparkles,RotateCcw} from 'lucide-react';
import {PlayerPortrait} from './player-portrait';
import {players,createAuctionOrder,money,bidIncrement} from '@/lib/game';
const stars=createAuctionOrder().slice(0,8).map(id=>players[id]);
export function AuctionShowcase(){
 const [index,setIndex]=useState(0),[price,setPrice]=useState(200),[sold,setSold]=useState(false);const scene=useRef<HTMLDivElement>(null);const player=stars[index];
 function next(n:number){setIndex((index+n+stars.length)%stars.length);setPrice(200);setSold(false)}
 function tilt(e:PointerEvent){if(e.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const box=e.currentTarget.getBoundingClientRect();scene.current?.style.setProperty('--tilt-x',`${-(e.clientY-box.top-box.height/2)/box.height*9}deg`);scene.current?.style.setProperty('--tilt-y',`${(e.clientX-box.left-box.width/2)/box.width*12}deg`)}
 return <div className="showcase" ref={scene} onPointerMove={tilt} onPointerLeave={()=>{scene.current?.style.setProperty('--tilt-x','0deg');scene.current?.style.setProperty('--tilt-y','0deg')}}><div className="showcase-halo halo-a"/><div className="showcase-halo halo-b"/><div className="showcase-ticket"><div className="showcase-top"><span><i/>THE AUCTION, IN YOUR HANDS</span><Sparkles size={18}/></div><div className={'showcase-stage '+(sold?'showcase-sold':'')}><div className="showcase-beam"/><span className="showcase-word" aria-hidden="true">DREAM<br/>BIG.</span><div className="showcase-player" key={player.id}><PlayerPortrait name={player.name}/></div>{sold&&<div className="showcase-stamp" role="status">SOLD TO YOUR DREAM TEAM</div>}<div className="showcase-plinth"/></div><div className="showcase-name"><button onClick={()=>next(-1)} aria-label="Previous preview player"><ArrowLeft size={18}/></button><span><small>₹2 CR MARQUEE CLUB</small><h2>{player.name}</h2></span><button onClick={()=>next(1)} aria-label="Next preview player"><ArrowRight size={18}/></button></div><div className="showcase-price" aria-live="polite"><span>{sold?'YOUR PRACTICE SIGNING':'YOUR PRACTICE BID'}</span><strong key={price}>{money(price)}</strong></div><div className="showcase-actions"><button onClick={()=>{if(sold){setSold(false);setPrice(200)}else setPrice(price+bidIncrement(price))}}>{sold?<RotateCcw size={16}/>:<Gavel size={16}/>} {sold?'Try again':`Raise ${money(bidIncrement(price))}`}</button><button onClick={()=>setSold(true)} disabled={sold}>{sold?'Hammer down!':'Drop the hammer'}</button></div><p>Try a bid. Feel the win. This is a preview—your purse is safe.</p></div><span className="showcase-caption">YOUR NEXT GREAT SIGNING STARTS HERE</span></div>
}
