'use client';
import {memo,useState,type CSSProperties} from 'react';
import {Pause,Play,ChevronDown,ChevronUp,Gavel} from 'lucide-react';
import {teams,money} from '@/lib/game';
type Props={player:string;phase:string;price:number;leader?:string|null;preview?:boolean;ambient?:boolean};
export const AuctionHall=memo(function AuctionHall({player,phase,price,leader,preview=false,ambient=false}:Props){
 const [paused,setPaused]=useState(false),[collapsed,setCollapsed]=useState(false);
 return <section className={`auction-hall ${paused?'hall-paused':''} ${collapsed?'hall-collapsed':''} ${preview?'hall-preview':''} ${ambient?'hall-ambient':''}`} aria-hidden={ambient||undefined} aria-label={preview?'Interactive auction hall preview':'Live auction hall'}>{!ambient&&<div className="hall-toolbar"><span><i/>{preview?'EXPLORE THE AUCTION HALL':'YOUR FRONT-ROW SEAT'}</span><div><button aria-label={paused?'Resume hall animation':'Pause hall animation'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={13}/>:<Pause size={13}/>}</button>{!preview&&<button aria-label={collapsed?'Expand auction hall':'Collapse auction hall'} aria-expanded={!collapsed} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronDown size={16}/>:<ChevronUp size={16}/>}</button>}</div></div>}<div className="hall-viewport"><div className="hall-world"><div className="hall-ceiling" aria-hidden="true"/><div className="hall-beam beam-left" aria-hidden="true"/><div className="hall-beam beam-right" aria-hidden="true"/><div className="hall-back-wall" aria-hidden="true"/><div className="hall-floor" aria-hidden="true"/><div className="hall-stage"><div className="hall-board" key={player}><small>{phase==='finished'?'THE AUCTION IS COMPLETE':phase==='lobby'?'ON THE BOARD · READY WHEN YOU ARE':phase==='sold'?(leader?'SOLD · HAMMER DOWN':'UNSOLD · NEXT LOT SHORTLY'):'NOW CALLING'}</small><strong>{phase==='finished'?'Dream teams assembled':player}</strong><span>{phase==='lobby'?'The host starts the auction':phase==='finished'?'Thank you, team owners':`${money(price)}${leader?' · '+leader:''}`}</span></div><div className={`auctioneer ${phase==='sold'?'hammer-sold':''}`} aria-hidden="true"><i className="auctioneer-head"/><i className="auctioneer-body"/><span className="auctioneer-arm"><Gavel size={20}/></span><i className="auctioneer-desk"/></div><div className="stage-edge" aria-hidden="true"/></div><div className="hall-delegations" aria-hidden="true">{teams.map((t,i)=><div className={`delegation ${leader===t.id?'delegation-leading':''}`} key={t.id} style={{'--delegation-color':t.color,'--seat':i} as CSSProperties}><div className="seated-people">{[0,1,2].map(n=><div className="seated-person" key={n}><i className="person-head"/><i className="person-body"/><i className="person-chair"/>{n===1&&<span className="person-paddle">{t.id}</span>}</div>)}</div><div className="delegation-table"><span>{t.id}</span><i/></div></div>)}</div></div><div className="hall-vignette" aria-hidden="true"/></div></section>
});
