'use client';
import {useEffect,useRef,useState} from 'react';
export function SiteEffects(){
 const [scroll,setScroll]=useState({progress:0,visible:false,down:true,moving:false});const track=useRef<HTMLDivElement>(null);
 useEffect(()=>{let previous=window.scrollY,idle:ReturnType<typeof setTimeout>,frame=0,card:HTMLElement|null=null;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const update=()=>{const max=document.documentElement.scrollHeight-innerHeight,y=window.scrollY;setScroll(s=>({progress:max>0?y/max:0,visible:max>10,down:y===previous?s.down:y>previous,moving:y!==previous}));previous=y;clearTimeout(idle);idle=setTimeout(()=>setScroll(s=>({...s,moving:false})),650)};
 const reset=()=>{if(card){card.removeAttribute('data-tilting');card.style.removeProperty('--card-x');card.style.removeProperty('--card-y');card=null}};
 const move=(e:PointerEvent)=>{if(e.pointerType!=='mouse'||reduced.matches)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const target=(e.target as HTMLElement).closest<HTMLElement>('.panel,.franchise-tile,.challenge-card,.discovery-path>button');if(card!==target)reset();card=target;if(!card)return;const r=card.getBoundingClientRect();card.dataset.tilting='true';card.style.setProperty('--card-x',`${-(e.clientY-r.top-r.height/2)/r.height*8}deg`);card.style.setProperty('--card-y',`${(e.clientX-r.left-r.width/2)/r.width*10}deg`);})};
 const observer=new ResizeObserver(update);observer.observe(document.body);document.documentElement.classList.add('cricket-scroll-enabled');window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);document.addEventListener('pointermove',move);document.addEventListener('pointerleave',reset);update();return()=>{observer.disconnect();clearTimeout(idle);cancelAnimationFrame(frame);reset();document.documentElement.classList.remove('cricket-scroll-enabled');window.removeEventListener('scroll',update);window.removeEventListener('resize',update);document.removeEventListener('pointermove',move);document.removeEventListener('pointerleave',reset)};
 },[]);
 function seek(y:number){const r=track.current!.getBoundingClientRect();window.scrollTo({top:Math.max(0,Math.min(1,(y-r.top)/r.height))*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'})}
 if(!scroll.visible)return null;
 return <div ref={track} className={'cricket-scroll '+(scroll.down?'batting':'bowling')+(scroll.moving?' is-moving':'')}><div className="cricket-thumb" style={{top:`${scroll.progress*100}%`}} role="scrollbar" aria-label="Page scroll" aria-controls="site-content" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(scroll.progress*100)} aria-orientation="vertical" tabIndex={0} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);seek(e.clientY)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))seek(e.clientY)}} onKeyDown={e=>{const offsets:Record<string,number>={ArrowDown:80,ArrowUp:-80,PageDown:innerHeight*.8,PageUp:-innerHeight*.8};if(e.key in offsets){e.preventDefault();window.scrollBy({top:offsets[e.key],behavior:'smooth'})}else if(e.key==='Home'||e.key==='End'){e.preventDefault();window.scrollTo({top:e.key==='Home'?0:document.documentElement.scrollHeight,behavior:'smooth'})}}}><svg className="scroll-cricketer" viewBox="0 0 60 70" aria-hidden="true"><circle cx="29" cy="12" r="7" fill="#fbd0a4"/><path d="M22 9Q29-3 36 9" stroke="#b6ff63" strokeWidth="6"/><path d="M28 23L27 43M27 43L12 62M27 43L44 62" stroke="#91d9ff" strokeWidth="8" strokeLinecap="round" fill="none"/><g className="cricket-arm"><path d="M29 26L43 31L48 19" stroke="#fbd0a4" strokeWidth="6" strokeLinecap="round" fill="none"/>{scroll.down?<path d="M47 22L54 2" stroke="#ffc778" strokeWidth="7" strokeLinecap="round"/>:<circle cx="48" cy="16" r="4" fill="#ff6286"/>}</g></svg><svg className="scroll-ball" viewBox="0 0 32 32" aria-hidden="true"><defs><radialGradient id="cricket-ball-light" cx="30%" cy="25%"><stop stopColor="#ff9fae"/><stop offset="1" stopColor="#c31349"/></radialGradient></defs><circle cx="16" cy="16" r="14" fill="url(#cricket-ball-light)"/><path d="M9 4Q25 16 9 28M12 3Q28 16 12 29" fill="none" stroke="#fff1d4" strokeWidth="1.3" strokeDasharray="2 2"/></svg></div></div>
}
