export const teams = [
  ['CSK','Chennai Super Kings','#ffd54a','Chennai'],['MI','Mumbai Indians','#56a8ff','Mumbai'],['RCB','Royal Challengers Bengaluru','#ff5a6c','Bengaluru'],['KKR','Kolkata Knight Riders','#b68aff','Kolkata'],['SRH','Sunrisers Hyderabad','#ff914d','Hyderabad'],['RR','Rajasthan Royals','#ff72b6','Jaipur'],['DC','Delhi Capitals','#6092ff','Delhi'],['PBKS','Punjab Kings','#ff6577','Punjab'],['GT','Gujarat Titans','#85c4c7','Ahmedabad'],['LSG','Lucknow Super Giants','#58dbc5','Lucknow']
].map(([id,name,color,city])=>({id,name,color,city}));
const names = [
 ['Rishabh Pant','WK','India'],['Shreyas Iyer','BAT','India'],['Jos Buttler','WK','England'],['Arshdeep Singh','BOWL','India'],['Mitchell Starc','BOWL','Australia'],['KL Rahul','WK','India'],['Yuzvendra Chahal','BOWL','India'],['Liam Livingstone','AR','England'],['Mohammed Shami','BOWL','India'],['David Miller','BAT','South Africa'],['Glenn Maxwell','AR','Australia'],['Mohammed Siraj','BOWL','India'],['Trent Boult','BOWL','New Zealand'],['Marcus Stoinis','AR','Australia'],['Ishan Kishan','WK','India'],['Venkatesh Iyer','AR','India'],['Phil Salt','WK','England'],['Devon Conway','BAT','New Zealand'],['Rahul Tripathi','BAT','India'],['Rachin Ravindra','AR','New Zealand'],['Aiden Markram','BAT','South Africa'],['Faf du Plessis','BAT','South Africa'],['Washington Sundar','AR','India'],['Ravichandran Ashwin','AR','India'],['Bhuvneshwar Kumar','BOWL','India'],['T Natarajan','BOWL','India'],['Deepak Chahar','BOWL','India'],['Harshal Patel','BOWL','India'],['Avesh Khan','BOWL','India'],['Prasidh Krishna','BOWL','India'],['Ravi Bishnoi','BOWL','India'],['Krunal Pandya','AR','India'],['Sam Curran','AR','England'],['Jofra Archer','BOWL','England'],['Quinton de Kock','WK','South Africa'],['Will Jacks','AR','England'],['Tim David','BAT','Australia'],['Nitish Rana','BAT','India'],['Abdul Samad','BAT','India'],['Abhinav Manohar','BAT','India'],['Shahbaz Ahmed','AR','India'],['Mahipal Lomror','AR','India'],['Anuj Rawat','WK','India'],['Jitesh Sharma','WK','India'],['Ashutosh Sharma','BAT','India'],['Nehal Wadhera','BAT','India'],['Naman Dhir','AR','India'],['Angkrish Raghuvanshi','BAT','India'],['Sameer Rizvi','BAT','India'],['Suyash Sharma','BOWL','India'],['Mukesh Kumar','BOWL','India'],['Khaleel Ahmed','BOWL','India'],['Akash Deep','BOWL','India'],['Ishant Sharma','BOWL','India'],['Umesh Yadav','BOWL','India'],['Jaydev Unadkat','BOWL','India'],['Mayank Agarwal','BAT','India'],['Manish Pandey','BAT','India'],['Ajinkya Rahane','BAT','India'],['Prithvi Shaw','BAT','India'],
 // Append-only IDs: existing saved room awards depend on the first 60 entries.
 // Sources and fantasy pricing notes: PLAYER_DATA.md
 ["Virat Kohli", "BAT", "India"],
 ["Rohit Sharma", "BAT", "India"],
 ["MS Dhoni", "WK", "India"],
 ["Jasprit Bumrah", "BOWL", "India"],
 ["Hardik Pandya", "AR", "India"],
 ["Suryakumar Yadav", "BAT", "India"],
 ["Ruturaj Gaikwad", "BAT", "India"],
 ["Sanju Samson", "WK", "India"],
 ["Shubman Gill", "BAT", "India"],
 ["Rashid Khan", "BOWL", "Afghanistan"],
 ["Rinku Singh", "BAT", "India"],
 ["Sunil Narine", "AR", "West Indies"],
 ["Nicholas Pooran", "WK", "West Indies"],
 ["Axar Patel", "AR", "India"],
 ["Kuldeep Yadav", "BOWL", "India"],
 ["Yashasvi Jaiswal", "BAT", "India"],
 ["Ravindra Jadeja", "AR", "India"],
 ["Prabhsimran Singh", "WK", "India"],
 ["Shashank Singh", "BAT", "India"],
 ["Travis Head", "BAT", "Australia"],
 ["Pat Cummins", "BOWL", "Australia"],
 ["Abhishek Sharma", "AR", "India"],
 ["Heinrich Klaasen", "WK", "South Africa"],
 ["Rajat Patidar", "BAT", "India"],
 ["Josh Hazlewood", "BOWL", "Australia"],
 ["Jake Fraser-McGurk", "BAT", "Australia"],
 ["Cameron Green", "BAT", "Australia"],
 ["Sarfaraz Khan", "BAT", "India"],
 ["Gus Atkinson", "AR", "England"],
 ["Wanindu Hasaranga", "AR", "Sri Lanka"],
 ["Deepak Hooda", "AR", "India"],
 ["Wiaan Mulder", "AR", "South Africa"],
 ["Finn Allen", "WK", "New Zealand"],
 ["Jonny Bairstow", "WK", "England"],
 ["K.S. Bharat", "WK", "India"],
 ["Ben Duckett", "WK", "England"],
 ["Rahmanullah Gurbaz", "WK", "Afghanistan"],
 ["Jamie Smith", "WK", "England"],
 ["Gerald Coetzee", "BOWL", "South Africa"],
 ["Jacob Duffy", "BOWL", "New Zealand"],
 ["Fazalhaq Farooqi", "BOWL", "Afghanistan"],
 ["Matt Henry", "BOWL", "New Zealand"],
 ["Spencer Johnson", "BOWL", "Australia"],
 ["Shivam Mavi", "BOWL", "India"],
 ["Anrich Nortje", "BOWL", "South Africa"],
 ["Matheesha Pathirana", "BOWL", "Sri Lanka"],
 ["Rahul Chahar", "BOWL", "India"],
 ["Akeal Hosein", "BOWL", "West Indies"],
 ["Mujeeb Rahman", "BOWL", "Afghanistan"],
 ["Maheesh Theekshana", "BOWL", "Sri Lanka"],
 ["Aarya Desai", "BAT", "India"],
 ["Yash Dhull", "BAT", "India"],
 ["Anmolpreet Singh", "BAT", "India"],
 ["Atharva Taide", "BAT", "India"],
 ["Abhinav Tejrana", "BAT", "India"],
 ["Auqib Dar", "AR", "India"],
 ["Rajvardhan Hangargekar", "AR", "India"],
 ["Tanush Kotian", "AR", "India"],
 ["Shivang Kumar", "AR", "India"],
 ["Kamlesh Nagarkoti", "AR", "India"],
 ["Vijay Shankar", "AR", "India"],
 ["Sanvir Singh", "AR", "India"],
 ["Edhen Tom", "AR", "India"],
 ["Prashant Veer", "AR", "India"],
 ["Ruchit Ahir", "WK", "India"],
 ["Vansh Bedi", "WK", "India"],
 ["Mukul Choudhary", "WK", "India"],
 ["Tushar Raheja", "WK", "India"],
 ["Kartik Sharma", "WK", "India"],
 ["Tejasvi Singh", "WK", "India"],
 ["Raj Limbani", "BOWL", "India"],
 ["Akash Madhwal", "BOWL", "India"],
 ["Sushant Mishra", "BOWL", "India"],
 ["Ashok Sharma", "BOWL", "India"],
 ["Simarjeet Singh", "BOWL", "India"],
 ["Naman Tiwari", "BOWL", "India"],
 ["Kartik Tyagi", "BOWL", "India"],
 ["Yash Raj Punja", "BOWL", "India"],
 ["Vignesh Puthur", "BOWL", "India"],
 ["Karn Sharma", "BOWL", "India"],
 ["Shivam Shukla", "BOWL", "India"],
 ["Kumar Kartikeya Singh", "BOWL", "India"],
 ["Prashant Solanki", "BOWL", "India"],
 ["Wahidullah Zadran", "BOWL", "Afghanistan"],
 ["Sediqullah Atal", "BAT", "Afghanistan"],
 ["Ackeem Auguste", "BAT", "West Indies"],
 ["Reeza Hendricks", "BAT", "South Africa"],
 ["Pathum Nissanka", "BAT", "Sri Lanka"],
 ["Tim Robinson", "BAT", "New Zealand"],
 ["Steve Smith", "BAT", "Australia"],
 ["Sean Abbott", "AR", "Australia"],
 ["Michael Bracewell", "AR", "New Zealand"],
 ["Ben Dwarshuis", "AR", "Australia"],
 ["Zak Foulkes", "AR", "New Zealand"],
 ["Jason Holder", "AR", "West Indies"],
 ["Daryl Mitchell", "AR", "New Zealand"],
 ["Daniel Sams", "AR", "Australia"],
 ["Dasun Shanaka", "AR", "Sri Lanka"],
 ["Matthew Short", "AR", "Australia"],
 ["Tom Banton", "WK", "England"],
 ["Jordan Cox", "WK", "England"],
 ["Shai Hope", "WK", "West Indies"],
 ["Josh Inglis", "WK", "Australia"],
 ["Benjamin McDermott", "WK", "Australia"],
 ["Kusal Mendis", "WK", "Sri Lanka"],
 ["Kusal Perera", "WK", "Sri Lanka"],
 ["Tim Seifert", "WK", "New Zealand"],
 ["Kyle Jamieson", "BOWL", "New Zealand"],
 ["Saqib Mahmood", "BOWL", "England"],
 ["Adam Milne", "BOWL", "New Zealand"],
 ["Lungisani Ngidi", "BOWL", "South Africa"],
 ["William Orourke", "BOWL", "New Zealand"],
 ["Mustafizur Rahman", "BOWL", "Bangladesh"],
 ["Chetan Sakariya", "BOWL", "India"],
 ["Kuldeep Sen", "BOWL", "India"],
 ["Qais Ahmad", "BOWL", "Afghanistan"],
 ["Rishad Hossain", "BOWL", "Bangladesh"],
 ["Mohammad Waqar Salamkheil", "BOWL", "Afghanistan"],
 ["Viyaskanth Vijayakanth", "BOWL", "Sri Lanka"],
 ["Ankit Kumar", "BAT", "India"],
 ["Rohan Kunnummal", "BAT", "India"],
 ["Danish Malewar", "BAT", "India"],
 ["Pukhraj Mann", "BAT", "India"],
 ["Salman Nizar", "BAT", "India"],
 ["Aman Rao Perala", "BAT", "India"],
 ["Akshat Raghuwanshi", "BAT", "India"],
 ["Manan Vohra", "BAT", "India"],
 ["Yuvraj Chaudhary", "AR", "India"],
 ["Satvik Deswal", "AR", "India"],
 ["Aman Khan", "AR", "India"],
 ["Darshan Nalkande", "AR", "India"],
 ["Vicky Ostwal", "AR", "India"],
 ["Sairaj Patil", "AR", "India"],
 ["Suyash Prabhudessai", "AR", "India"],
 ["Mayank Rawat", "AR", "India"],
 ["Harsh Tyagi", "AR", "India"],
 ["Mangesh Yadav", "AR", "India"],
 ["Salil Arora", "WK", "India"],
 ["Ricky Bhui", "WK", "India"],
 ["Rahul Buddhi", "WK", "India"],
 ["Saurav Chuahan", "WK", "India"],
 ["Yashvardhan Dalal", "WK", "India"],
 ["Abhishek Pathak", "WK", "India"],
 ["Kunal Rathore", "WK", "India"],
 ["Ravi Singh", "WK", "India"],
 ["K.M Asif", "BOWL", "India"],
 ["Sakib Hussain", "BOWL", "India"],
 ["Mohammad Izhar", "BOWL", "India"],
 ["Vidwath Kaverappa", "BOWL", "India"],
 ["Vijay Kumar", "BOWL", "India"],
 ["Vidyadhar Patil", "BOWL", "India"],
 ["PV.Satyanarayana Raju", "BOWL", "India"],
 ["Onkar Tarmale", "BOWL", "India"],
 ["Prithviraj Yarra", "BOWL", "India"],
 ["Shubham Agrawal", "BOWL", "India"],
 ["Murugan Ashwin", "BOWL", "India"],
 ["Tejas Baroka", "BOWL", "India"],
 ["K.C. Cariappa", "BOWL", "India"],
 ["Kartik Chadha", "BOWL", "India"],
 ["Pravin Dubey", "BOWL", "India"],
 ["Mohit Rathee", "BOWL", "India"],
 ["Himanshu Sharma", "BOWL", "India"],
 ["Bailapudi Yeswanth", "BOWL", "India"],
 ["Rehan Ahmed", "AR", "England"],
 ["Cooper Connolly", "AR", "Australia"],
 ["Tom Curran", "AR", "England"],
 ["Bevon-John Jacobs", "AR", "New Zealand"],
 ["Daniel Lawrence", "AR", "England"],
 ["George Linde", "AR", "South Africa"],
 ["Gulbadin Naib", "AR", "Afghanistan"],
 ["William Sutherland", "AR", "Australia"],
 ["Beau Webster", "AR", "Australia"],
 ["Taskin Ahmed", "BOWL", "Bangladesh"],
 ["Richard Gleeson", "BOWL", "England"],
 ["Alzarri Joseph", "BOWL", "West Indies"],
 ["Shamar Joseph", "BOWL", "West Indies"],
 ["Riley Meredith", "BOWL", "Australia"],
 ["Jhye Richardson", "BOWL", "Australia"],
 ["Navdeep Saini", "BOWL", "India"],
 ["Naveen Ul Haq", "BOWL", "Afghanistan"],
 ["Luke Wood", "BOWL", "England"],
 ["Kunal Chandela", "BAT", "India"],
 ["Ayush Doseja", "BAT", "India"],
 ["Qamran Iqbal", "BAT", "India"],
 ["M.Dheeraj Kumar", "BAT", "India"],
 ["Bhanu Pania", "BAT", "India"],
 ["Sahil Parakh", "BAT", "India"],
 ["Arsh Kabir Ranga", "BAT", "India"],
 ["Adarsh Singh", "BAT", "India"],
 ["Manoj Bhandage", "AR", "India"],
 ["Mayank Dagar", "AR", "India"],
 ["Raghav Goyal", "AR", "India"],
 ["Manvanth Kumar", "AR", "India"],
 ["Abid Mushtaq", "AR", "India"],
 ["Jalaj Saxena", "AR", "India"],
 ["Atit Sheth", "AR", "India"],
 ["Hritik Shokeen", "AR", "India"],
 ["Jagadeesha Suchith", "AR", "India"],
 ["Tanay Thyagarajann", "AR", "India"],
 ["Joe Clarke", "WK", "England"],
 ["Connor Esterhuizen", "WK", "South Africa"],
 ["Ajitesh Guruswamy", "WK", "India"],
 ["Siddharth Joon", "WK", "India"],
 ["Tom Moores", "WK", "England"],
 ["Bipin Saurabh", "WK", "India"],
 ["Vishnu Solanki", "WK", "India"],
 ["Hardik Tamore", "WK", "India"],
 ["Sayan Ghosh", "BOWL", "India"],
 ["Money Grewal", "BOWL", "India"],
 ["Arpit Guleria", "BOWL", "India"],
 ["Sunil Kumar", "BOWL", "India"],
 ["Tristan Luus", "BOWL", "South Africa"],
 ["Divesh Sharma", "BOWL", "India"],
 ["Abhilash Shetty", "BOWL", "India"],
 ["Irfan Umair", "BOWL", "India"],
 ["Kuldip Yadav", "BOWL", "India"],
 ["Manan Bhardwaj", "BOWL", "India"],
 ["Shreyas Chavan", "BOWL", "India"],
 ["Parikshit Dhanak", "BOWL", "India"],
 ["Chintal Gandhi", "BOWL", "India"],
 ["Dharmendrasinh Jadeja", "BOWL", "India"],
 ["Amit Kumar", "BOWL", "India"],
 ["Vishal Nishad", "BOWL", "India"],
 ["Saumy Pandey", "BOWL", "India"],
 ["Jhathavedh Subramanyan", "BOWL", "India"],
 ["Muhammad Abbas", "AR", "New Zealand"],
 ["Charith Asalanka", "AR", "Sri Lanka"],
 ["Roston Chase", "AR", "West Indies"],
 ["Liam Dawson", "AR", "England"],
 ["George Garton", "AR", "England"],
 ["Kyle Mayers", "AR", "West Indies"],
 ["Dwaine Pretorius", "AR", "South Africa"],
 ["Nathan Smith", "AR", "New Zealand"],
 ["Dunith Wellalage", "AR", "Sri Lanka"],
 ["Jason Behrendorff", "BOWL", "Australia"],
 ["Tanzim Hasan Sakib", "BOWL", "Bangladesh"],
 ["Matthew Potts", "BOWL", "England"],
 ["Nahid Rana", "BOWL", "Bangladesh"],
 ["Olly Stone", "BOWL", "England"],
 ["Joshua Tongue", "BOWL", "England"],
 ["Sandeep Warrier", "BOWL", "India"],
 ["Sachin Dhas", "BAT", "India"],
 ["Miles Hammond", "BAT", "India"],
 ["Ahammed Imran", "BAT", "India"],
 ["Vishvarajsinh Jadeja", "BAT", "India"],
 ["Ayaz Khan", "BAT", "India"],
 ["Daniel Lategan", "BAT", "England"],
 ["Siddhant Rana", "BAT", "India"],
 ["Aaron Varghese", "BAT", "India"],
 ["Atharva Ankolekar", "AR", "India"],
 ["Abdul Bazith", "AR", "India"],
 ["Karan Lal", "AR", "India"],
 ["Shams Mulani", "AR", "India"],
 ["Ripal Patel", "AR", "India"],
 ["Prince Rai", "AR", "India"],
 ["Vivrant Sharma", "AR", "India"],
 ["Utkarsh Singh", "AR", "India"],
 ["Ayush Vartak", "AR", "India"],
 ["Sanjay Yadav", "AR", "India"],
 ["Sayed Irfan Aftab", "BOWL", "India"],
 ["Esakkimuthu Ayyakutti", "BOWL", "India"],
 ["Praful Hinge", "BOWL", "India"],
 ["Pankaj Jaswal", "BOWL", "India"],
 ["Kulwant Khejroliya", "BOWL", "India"],
 ["Ravi Kumar", "BOWL", "India"],
 ["Rajan Kumar", "BOWL", "India"],
 ["Safvan Patel", "BOWL", "India"],
 ["Ishan Porel", "BOWL", "India"],
 ["Purav Agarwal", "BOWL", "India"],
 ["Jikku Bright", "BOWL", "India"],
 ["Yash Dicholkar", "BOWL", "India"],
 ["Arab Gul", "BOWL", "Afghanistan"],
 ["Rakibul Hasan", "BOWL", "Bangladesh"],
 ["Traveen Mathew", "BOWL", "Sri Lanka"],
 ["Naman Pushpak", "BOWL", "India"],
 ["Izaz Sawariya", "BOWL", "India"],
 ["Roshan Wagshare", "BOWL", "India"],
 ["Wesley Agar", "BOWL", "Australia"],
 ["Binura Fernando", "BOWL", "Sri Lanka"],
 ["Md Shoriful Islam", "BOWL", "Bangladesh"],
 ["Joshua Little", "BOWL", "Ireland"],
 ["Obed McCoy", "BOWL", "West Indies"],
 ["Billy Stanlake", "BOWL", "Australia"],
 ["R.S Ambrish", "AR", "India"],
 ["Nikhil Chaudhary", "AR", "India"],
 ["Krains Fuletra", "AR", "India"],
 ["Macneil Noronha", "AR", "India"],
 ["R Rajkumar", "AR", "India"],
 ["Ninad Rathva", "AR", "India"],
 ["Sunny Sandhu", "AR", "India"],
 ["Shivalik Sharma", "AR", "India"],
 ["Siddharth Yadav", "AR", "India"],
 ["R.Sonu Yadav", "AR", "India"],
 ["Waseem Khanday", "BOWL", "India"],
 ["Atif Mushtaq", "BOWL", "India"],
 ["Atal Rai", "BOWL", "India"],
 ["C.Rakshann Readdi", "BOWL", "India"],
 ["Manish Reddy", "BOWL", "India"],
 ["Nishanth Saranu", "BOWL", "India"],
 ["Deependra Singh", "BOWL", "India"],
 ["Rajat Verma", "BOWL", "India"],
 ["Rohit Yadav", "BOWL", "India"],
 ["Emanjot Chahal", "AR", "India"],
 ["Shubhang Hegde", "AR", "India"],
 ["Bal Krishna", "AR", "India"],
 ["Vihaan Malhotra", "AR", "India"],
 ["Khilan Patel", "AR", "India"],
 ["Delano Potgieter", "AR", "South Africa"],
 ["Hardik Raj", "AR", "India"],
 ["Sarthak Ranjan", "AR", "India"],
 ["Parth Rekhade", "AR", "India"],
 ["Tiaan Van Vuuren", "AR", "South Africa"],
 ["Shreevatsha Acharya", "BOWL", "India"],
 ["Sadek Hussain", "BOWL", "India"],
 ["Shubham Kapse", "BOWL", "India"],
 ["Aaqib Khan", "BOWL", "India"],
 ["Sabir Khan", "BOWL", "India"],
 ["Bayanda Majola", "BOWL", "South Africa"],
 ["Srihari Nair", "BOWL", "India"],
 ["Brijesh Sharma", "BOWL", "India"],
 ["Aman Shekhawat", "BOWL", "India"],
 ["Himanshu Bisht", "AR", "India"],
 ["Shreyan Chakraborty", "AR", "India"],
 ["Kanishk Chouhan", "AR", "India"],
 ["Mayank Gusain", "AR", "India"],
 ["Akash Pugazhanthi", "AR", "India"],
 ["Abhimanyusingh Rajput", "AR", "India"],
 ["Shubham Rana", "AR", "India"],
 ["Arpit Rana", "AR", "India"],
 ["Maramreddy Reddy", "AR", "India"],
 ["Sagar Solanki", "AR", "India"],
 ["Aryaman Singh Dhaliwal", "AR", "India"],
 ["Daksh Kamra", "AR", "India"],
 ["Vishal Mandwal", "AR", "India"],
 ["Arfaz Mohammad", "AR", "India"],
 ["Hemang Patel", "AR", "India"],
 ["Mridul Surroch", "AR", "India"],
 ["Anuj Thakral", "AR", "India"],
 ["Parth Vats", "AR", "India"],
 ["Lalit Yadav", "AR", "India"],
 ["Nitin Sai Yadav", "AR", "India"],
 ["Krish Bhagat", "AR", "India"],
 ["Prerit Dutta", "AR", "India"],
 ["Sammar Gajjar", "AR", "India"],
 ["Nasir Lone", "AR", "India"],
 ["Ishan Mulchandani", "AR", "India"],
 ["Akhil Scaria", "AR", "India"],
 ["Muhammed Sharafuddeen", "AR", "India"],
 ["K.Ajay Singh", "AR", "India"],
 ["Ritik Tada", "AR", "India"],
 ["Luckyrajsinh Vaghela", "AR", "India"],
 ["Mohamed Ali", "AR", "India"],
 ["Madhav Bajaj", "AR", "India"],
 ["Akshu Bajwa", "AR", "India"],
 ["Varun Raj Singh Bisht", "AR", "India"],
 ["Rishabh Chauhan", "AR", "India"],
 ["Jack Edwards", "AR", "Australia"],
 ["Dian Forrester", "AR", "South Africa"],
 ["Dhurmil Matkar", "AR", "India"],
 ["Shiva Singh", "AR", "India"],
 ["Parikshit Valsangkar", "AR", "India"],
 ["Vaibhav Sooryavanshi","BAT","India"],
 ["Kagiso Rabada","BOWL","South Africa"],
 ["Sai Sudharsan","BAT","India"],
];
// Curated fantasy marquee set: original marquee names plus retained stars and recent IPL leaders.
export const marqueeNames=new Set([...names.slice(0,18).map(p=>p[0]),...names.slice(60,85).map(p=>p[0]),'Bhuvneshwar Kumar','Jofra Archer','Prasidh Krishna','Vaibhav Sooryavanshi','Kagiso Rabada','Sai Sudharsan']);
export const players = names.map(([name,role,country],id)=>({id,name,role,country,marquee:marqueeNames.has(name),base:marqueeNames.has(name)?200:id<40?100:30,value:marqueeNames.has(name)?1100+(id*173)%900:200+(id*139)%700}));
export const createAuctionOrder=()=>[...players.filter(p=>p.marquee),...players.filter(p=>!p.marquee)].map(p=>p.id);
export const auctionPlayers=(g:Game)=>(g.order||players.map(p=>p.id)).map(id=>players[id]);
export const currentPlayer=(g:Game)=>players[g.order?.[g.index]??g.index];
export const lotOf=(g:Game,id:number)=>g.order?g.order.indexOf(id):id;
export const bidIncrement=(price:number)=>price<100?10:price<500?20:price<1000?25:30;

export const money = (n:number)=>`₹${(n/100).toFixed(2)} Cr`;
export type Seat = {name:string,token:string,bot:boolean,purse:number,squad:{player:number,price:number}[]};
export type Game = {order?:number[];code:string,host:string,phase:'lobby'|'live'|'sold'|'finished',seats:Record<string,Seat>,index:number,price:number,leader:string|null,deadline:number,nextBot:number,passed:string[],log:string[],round:number};
export const nextPrice=(g:Game)=>g.leader?g.price+bidIncrement(g.price):currentPlayer(g)?.base||30;
export function canBid(g:Game,id:string){const s=g.seats[id],p=currentPlayer(g);return !!s&&!!p&&s.purse>=nextPrice(g)&&s.squad.length<25&&(p.country==='India'||s.squad.filter(x=>players[x.player].country!=='India').length<8)&&g.leader!==id&&!g.passed.includes(id)}
export function bid(g:Game,id:string,now:number){g.price=nextPrice(g);g.leader=id;g.deadline=now+10000;g.nextBot=now+1800+Math.random()*1800;g.log.unshift(`${id} bid ${money(g.price)} for ${currentPlayer(g).name}`);g.log=g.log.slice(0,40)}
export function advance(g:Game,now:number){
 if(g.phase==='sold'&&now>=g.deadline){g.index++;g.round++;g.price=0;g.leader=null;g.passed=[];g.phase=g.index>=(g.order?.length||players.length)?'finished':'live';g.deadline=now+14000;g.nextBot=now+2500}
 if(g.phase!=='live')return;
 if(now>=g.deadline){if(g.leader){const s=g.seats[g.leader];s.purse-=g.price;s.squad.push({player:currentPlayer(g).id,price:g.price});g.log.unshift(`SOLD • ${currentPlayer(g).name} → ${g.leader} for ${money(g.price)}`)}else g.log.unshift(`UNSOLD • ${currentPlayer(g).name}`);g.phase='sold';g.deadline=now+3500;return}
 if(now>=g.nextBot){const eligible=teams.filter(t=>g.seats[t.id]?.bot&&canBid(g,t.id)&&nextPrice(g)<=currentPlayer(g).value*(0.72+((g.index+t.id.charCodeAt(0))%7)/10));if(eligible.length)bid(g,eligible[Math.floor(Math.random()*eligible.length)].id,now);else g.nextBot=now+2000}
}

// A record is announced only for a completed, awarded sale, never a live bid.
export function isRecordSale(g:Game){
 if(g.phase!=='sold'||!g.leader)return false;
 const sale=g.seats[g.leader]?.squad.find(s=>s.player===currentPlayer(g)?.id);
 if(!sale)return false;
 const previous=Object.values(g.seats).flatMap(s=>s.squad).filter(s=>lotOf(g,s.player)<g.index);
 return previous.length>0&&sale.price>Math.max(...previous.map(s=>s.price));
}

// Only completed lots have outcomes; a live leader is not yet a sale.
export function auctionResults(g:Game){
 const completed=g.phase==='finished'?Math.min(g.index,players.length):g.index+(g.phase==='sold'?1:0);
 const awards=new Map(Object.entries(g.seats).flatMap(([id,seat])=>seat.squad.map(s=>[s.player,{team:teams.find(t=>t.id===id),price:s.price}] as const)));
 return auctionPlayers(g).slice(0,completed).map(player=>({player,team:awards.get(player.id)?.team,price:awards.get(player.id)?.price||0})).reverse();
}
